services:
  movie:
      image: mysql
      container_name: MovieDB
      ports:
          - "3306:3306"
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./movie_scripts:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: pw